### ISSUE TITLE
unhandled parsing error: BW 304094

### ISSUE THREAD

**Issue by skenaja** [dchaplinsky/german_registry_parser#6]
```
{"notice_id":"304094","federal_state":"bw","amtsgericht":"Freiburg","aktenzeichen":"HRB 413275","posted_on":"2012-05-14","event_type":"Veränderungen","event_date":"2012-05-10","name":"GoForm GmbH","sitz":null,"inhaber":null,"gesellschafter":null,"rechtsform":null,"full_text":"Amtsgericht Freiburg Aktenzeichen: HRB 413275   \nBekannt gemacht am: 14.05.2012 12:00 Uhr\n\n\n\n\nIn () gesetzte Angaben der Anschrift und des Geschäftszweiges erfolgen ohne Gewähr.\nVeränderungen\n10.05.2012\n\nGoForm GmbH, Rheinfelden Baden, Adolf-Senger-Straße 10, 79618 Rheinfelden Baden. Nicht mehr Geschäftsführer: Meyer, Jana, geb. Wacek, Rheinfelden (Schweiz), *24.06.1946. Bestellt als Geschäftsführer: Janocha geb. geb. Schmidt, Christine, Lörrach, *17.12.1957; Schmidt, Hansjörg, Schopfheim, *14.04.1960.","url":"https://www.handelsregisterbekanntmachungen.de/en/skripte/hrb.php?rb_id=304094\u0026land_abk=bw"}
```

```
Traceback (most recent call last):
  File "pipeline.py", line 163, in <module>
    parsing_result, _ = parse_document(p_doc)
  File "registry_parser.py", line 518, in parse_document
    res[v.kind].append(v.to_dict())
  File "registry_parser.py", line 213, in to_dict
    self.payload["lastname"], self.payload["maidenname"] = self.payload["lastname"].split(" geborene")
ValueError: too many values to unpack (expected 2)
```

**Comment by dchaplinsky** [comment]
Exception was due to unexpected input (geb. geb. repeated).

Fixed now
